baseURL = 'https://ad-bean.github.io/'
relativeURLs = true

defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
title = "Adbean's Blog"

theme = "LoveIt"

[author]
  name = "Adbean"
  email = "adbeanx@outlook.com"
  link = "https://github.com/ad-bean"

[params]
  version = "0.2.X"
  description = "Adbean's Blog"
  [params.page.math]
    enable = true
  [params.home]
      [params.home.profile]
          enable = true
          # 主页显示头像的 URL
          gravatarEmail = ""
          avatarURL = "/avatar.png"
          subtitle = "Stay Hungry Stay Foolish"
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = "/Owl.ico"
      name = "Adbean's Blog"
      pre = ""
      post = ""
      typeit = false
  [params.app]
      title = "Adbean's Blog"
      svgFavicon = "/Owl.ico"
  [params.social]
    GitHub = "ad-bean"
    Linkedin = "yuxuan-liao-adbean"
    Email = "adbeanx@outlook.com"
  [params.home.posts]
    enable = true
    paginate = 10
    defaultHiddenFromHomePage = false
  [params.search]
    enable = true
    type = "lunr" 
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 50
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = "blog"
      appID = "OKDXG1V1ML"
      searchKey = "d36cbd4755f8bf0c3fc49bb46f4b8f8a"
[menu]
  [[menu.main]]
    identifier = "main"
    pre = ""
    post = ""
    name = "主页"
    url = "/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "文章"
    url = "/posts/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
#  [[menu.main]]
#    identifier = "categories"
#    pre = ""
#    post = ""
#    name = "分类"
#    url = "/categories/"
#    title = ""
#    weight = 4

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]