baseURL = 'https://ad-bean.github.io/'
relativeURLs = true

defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
title = "Adbean's Blog"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"

[author]
  name = "Adbean"
  email = "adbeanx@outlook.com"
  link = "https://github.com/ad-bean"

[params]
  version = "0.2.X"
  description = "Adbean's Blog"
  [params.math]
      # 开启数学公式
      enable = true
  [params.home]
      # 主页个人信息
      [params.home.profile]
          enable = true
          # 主页显示头像的 URL
          gravatarEmail = ""
          avatarURL = "/avatar.png"
          subtitle = "Stay Hungry Stay Foolish"
  [params.header]
    # 桌面端导航栏模式 ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # 移动端导航栏模式 ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt 新增 | 0.2.0 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = "/Owl.ico"
      # 标题名称
      name = "Adbean's Blog"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
      typeit = false
  [params.app]
      title = "Adbean's Blog"
      svgFavicon = "/Owl.ico"
  [params.social]
    GitHub = "ad-bean"
    Linkedin = "yuxuan-liao-adbean"
    Email = "adbeanx@outlook.com"
  [params.home.posts]
    enable = true
    # 主页每页显示文章数量
    paginate = 10
    # LoveIt 删除 | 0.2.0 被 params.page 中的 hiddenFromHomePage 替代
    # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
    defaultHiddenFromHomePage = false
  [params.search]
    enable = true
    type = "algolia" # 搜索引擎的类型 ["lunr", "algolia"]
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    # LoveIt 新增 | 0.2.1 最大结果数目
    maxResultLength = 10
    # LoveIt 新增 | 0.2.3 结果内容片段长度
    snippetLength = 50
    # LoveIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # LoveIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
    [params.search.algolia]
      index = "blog"
      appID = "OKDXG1V1ML"
      searchKey = "d36cbd4755f8bf0c3fc49bb46f4b8f8a"
[menu]
  [[menu.main]]
    identifier = "main"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "主页"
    url = "/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 4

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
